# Generated by Django 6.0.2 on 2026-02-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_role_personalprofile_shelterprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("personal", "Personal account"), ("shelter", "Shelter")],
                default="personal",
                max_length=20,
            ),
        ),
    ]
