# Generated by Django 6.0.2 on 2026-02-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelterprofile",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelterprofile",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
