# Generated by Django 6.0.2 on 2026-02-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_passwordreset"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelterprofile",
            name="tax_id",
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email адреса"
            ),
        ),
    ]
