# Generated by Django 6.0.2 on 2026-03-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_shelterprofile_tax_id_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="viber_phone_number",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
