# Generated by Django 6.0.2 on 2026-04-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_user_viber_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalprofile",
            name="full_name",
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
