# Generated by Django 6.0.2 on 2026-02-18 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField()),
                ("main_image", models.ImageField(upload_to="media")),
                ("location", models.CharField(max_length=256)),
                (
                    "age",
                    models.CharField(
                        choices=[
                            ("puppy", "Puppy (0–6/12 months)"),
                            ("junior", "Junior (6 months – 2 years)"),
                            ("adult", "Adult/Mature (1–7 years)"),
                            ("senior", "Senior (6–10+ years)"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "pet_type",
                    models.CharField(
                        choices=[
                            ("dog", "Dog"),
                            ("cat", "Cat"),
                            ("hamster", "Hamster"),
                            ("rabbit", "Rabbit"),
                            ("other", "Other"),
                        ],
                        default="dog",
                        max_length=64,
                    ),
                ),
                (
                    "pet_type_details",
                    models.CharField(
                        blank=True,
                        help_text="Please specify pet type if the main type field is 'Other'.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("black", "Black"),
                            ("white", "White"),
                            ("gray", "Gray"),
                            ("ginger", "Ginger"),
                            ("brown", "Brown"),
                            ("beige", "Beige"),
                            ("tricolor", "Tricolor"),
                            ("spotted", "Spotted"),
                            ("other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "color_details",
                    models.CharField(
                        blank=True,
                        help_text="Please specify color if the main color field is 'Other'",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("breed", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kg",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("is_purebred", models.BooleanField(default=False)),
                ("is_sterilized", models.BooleanField(default=False)),
                ("is_vaccinated", models.BooleanField(default=False)),
            ],
        ),
    ]
