# Generated by Django 6.0.2 on 2026-02-18 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pets", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="pet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ads",
                to="pets.pet",
            ),
        ),
    ]
