# Generated by Django 6.0.2 on 2026-02-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="main_image",
            field=models.ImageField(upload_to="media"),
        ),
    ]
