# Generated by Django 6.0.2 on 2026-02-19 13:09

import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_petlisting_delete_ad_delete_pet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petlisting",
            name="main_image",
            field=models.ImageField(upload_to=pets.models.create_custom_path),
        ),
    ]
