# Generated by Django 6.0.2 on 2026-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0004_alter_petlisting_main_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="petlisting",
            name="color_details",
        ),
        migrations.RemoveField(
            model_name="petlisting",
            name="description",
        ),
        migrations.RemoveField(
            model_name="petlisting",
            name="is_purebred",
        ),
        migrations.RemoveField(
            model_name="petlisting",
            name="pet_type_details",
        ),
        migrations.RemoveField(
            model_name="petlisting",
            name="weight",
        ),
        migrations.AddField(
            model_name="petlisting",
            name="about",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="petlisting",
            name="has_passport",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petlisting",
            name="special_needs",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="petlisting",
            name="story",
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="age",
            field=models.CharField(
                choices=[
                    ("puppy", "Puppy (0–12 months)"),
                    ("junior", "Junior (1 - 2 years)"),
                    ("adult", "Adult (3–5 years)"),
                    ("senior", "Senior (5+ years)"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="breed",
            field=models.CharField(
                choices=[
                    ("no_breed", "No breed"),
                    ("mongrel", "Mongrel"),
                    ("purebred", "Purebred"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="color",
            field=models.CharField(
                choices=[
                    ("white", "White"),
                    ("beige", "Beige"),
                    ("gray", "Gray"),
                    ("black", "Black"),
                    ("ginger", "Ginger"),
                    ("brown", "Brown"),
                    ("brindle", "Brindle"),
                    ("spotted", "Spotted"),
                    ("two_color", "Two colored"),
                    ("tricolor", "Tricolor"),
                    ("multicolor", "Multicolored"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="location",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="pet_type",
            field=models.CharField(
                choices=[
                    ("dog", "Dog"),
                    ("cat", "Cat"),
                    ("hamster", "Hamster"),
                    ("bird", "Bird"),
                    ("fish", "Fish"),
                    ("other", "Other"),
                ],
                default="dog",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="petlisting",
            name="status",
            field=models.CharField(
                choices=[
                    ("looking_for_a_home", "Looking for a home"),
                    ("help_needed", "Help needed"),
                ],
                default="looking_for_a_home",
                max_length=32,
            ),
        ),
    ]
