# Generated by Django 6.0.2 on 2026-02-26 21:33

import django.db.models.deletion
import pets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0005_remove_petlisting_color_details_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetListingImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=pets.models.create_custom_path_pet_listing_image)),
                (
                    "pet_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="pets.petlisting",
                    ),
                ),
            ],
        ),
    ]
