# Generated by Django 6.0.2 on 2026-03-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0006_petlistingimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="petlisting",
            name="is_helped",
            field=models.BooleanField(default=False),
        ),
    ]
