# Generated by Django 6.0.2 on 2026-03-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0007_petlisting_is_helped"),
    ]

    operations = [
        migrations.AddField(
            model_name="petlisting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
