# Generated by Django 6.0.2 on 2026-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0008_petlisting_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="petlisting",
            name="size",
            field=models.CharField(
                choices=[
                    ("looking_for_a_home", "Looking for a home"),
                    ("help_needed", "Help needed"),
                ],
                default="m",
                max_length=32,
            ),
        ),
    ]
